extensions:
  bearertokenauth:
    token: "${env:OTEL_BEARER_TOKEN}"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: bearertokenauth
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: bearertokenauth

processors:
  batch:
    timeout: 15s
    send_batch_size: 1024

  resource:
    attributes:
      - key: deployment.environment
        value: personal
        action: upsert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
    metric_expiration: 90m

  otlp_http/loki:
    endpoint: http://loki:3100/otlp

service:
  extensions: [bearertokenauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp_http/loki]
